hyper:
  lr: 0.001
  epochs: 20
  batch_size: 64
  step_size: 15
  gamma: 0.1
  log_interval: 10
  sigma_prior: 0.1
  mu_prior: 0
  weight_decay: 0.001
  dropout_prob: 0.0
model:
  #
  # name: "BNN"
  # name: "FFNN_simple"
  # name: "FFNN_MCD"
  name: "FFNN_DeepEnsemble"
  # name: "BatchEnsemble_FFNN"
  # name: "FFNN_Rank1"

  # name: "ConvolutionalBNN"
  # name: "BatchEnsemble_CNN"
  # name: "Simple_rank1_CNN"
  # name: "CNN_simple"
  # name: "CNN_MCD"
  # name: "CNN_DeepEnsemble"
  # image_size: 32
  image_size: 28
  ensemble_size: 10
  num_classes: 10
  num_models: 10
  input_size: 54
  output_size: 7
  # hidden_sizes: [64, 128, 256]
  # hidden_sizes: [64, 128, 256, 128, 64]
  # hidden_sizes: [64, 128, 256, 512, 1024]
  hidden_sizes: [512, 256, 128, 64]

  # conv_layers: [[1, 64, 3, 1, 1, 0.0, True], [64, 128, 3, 1, 1, 0.0, True], [128, 256, 3, 1, 1, 0.0, True]] 
                                                  #  (256, 256, 3, 1, 1, 0.2, False), (256, 256, 3, 1, 1, 0.2, False), (256, 256, 3, 1, 1, 0.2, False)]

# For ConvolutionalBNN layer: [in_channels, out_channels, kernel_size, stride, padding, pooling]
  # conv_layers: [[1, 64, 3, 1, 1, True], [64, 128, 3, 1, 1, True], [128, 256, 3, 1, 1, True]]
                # [256, 256, 3, 1, 1, False], [256, 256, 3, 1, 1, False], [256, 256, 3, 1, 1, False]]

  #BatchEnsemble
  conv_layers: [[1, 64, 3, 10, 1, 1], [64, 128, 3, 10, 1, 1], [128, 256, 3, 10, 1, 1]]

  #Rank 1
  # conv_layers: [[1, 64, 3, 10, 1, 1, True], [64, 128, 3, 10, 1, 1, True], [128, 256, 3, 10, 1, 1, True]]
  #               [256, 256, 3, 10, 1, 1, False], [256, 256, 3, 10, 1, 1, False], [256, 256, 3, 10, 1, 1, False]]
  #conv_layers: [[1, 64, 3, 9, 1, 1], [64, 128, 3, 9, 1, 1], [128, 256, 3, 9, 1, 1]]
  # conv_layers: [[3, 64, 3, 1, 1], [64, 128, 3, 1, 1], [128, 256, 3, 1, 1]]
data:
  # dataset_name: "cifar10"
  # dataset_name: "mnist"
  dataset_name: "forest_cover"
constants:
  seed: 42
  patience: 5
  input_dim: 784
  output_dim: 10
  data_path: "data/"
wandb:
  project: "uncertainty_quantification"
  entity: "andr917d"
bsub:
  queue: "gpua100"
  # name: "ConvolutionalBNN"
  # name: "BatchEnsemble_CNN"
  # name: "Rank1_CNN"
  # name: "Simple_CNN"
  # name: "CNN_MCD"
  # name: "CNN_DeepEnsemble"
  # name: "BNN"
  # name: "BatchEnsemble_FFNN"
  # name: "Rank1_FFNN"
  # name: "simple_FFNN"
  # name: "FFNN_MCD"
  name: "FFNN_DeepEnsemble"
  gpu_num: 1
  cpu_num: 4
  cpu_mem: 4