hyper:
  lr: 0.01
  epochs: 15
  batch_size: 64
  step_size: 50
  gamma: 0.1
  log_interval: 10
model:
  name: "Simple_rank1_CNN"
  image_size: 32
  num_classes: 10
  # conv_layers: [(3, 64, 3, 1, 1, 0.2, True), (64, 128, 3, 1, 1, 0.2, True), (128, 256, 3, 1, 1, 0.2, True), 
  #                                                  (256, 256, 3, 1, 1, 0.2, False), (256, 256, 3, 1, 1, 0.2, False), (256, 256, 3, 1, 1, 0.2, False)]
  # conv_layers: [[3, 64, 3, 1, 1, 0.2, True], [64, 128, 3, 1, 1, 0.2, True], [128, 256, 3, 1, 1, 0.2, True], 
  #             [256, 256, 3, 1, 1, 0.2, False], [256, 256, 3, 1, 1, 0.2, False], [256, 256, 3, 1, 1, 0.2, False]]
  conv_layers: [[3, 64, 3, 10, 1, 1], [64, 128, 3, 10, 1, 1], [128, 256, 3, 10, 1, 1]]
  # conv_layers: [[3, 64, 3, 1, 1], [64, 128, 3, 1, 1], [128, 256, 3, 1, 1]]
data:
  dataset_name: "cifar10"
constants:
  seed: 42
  patience: 5
  input_dim: 784
  output_dim: 10
  data_path: "data/"
wandb:
  project: "uncertainty_quantification"
  entity: "andr917d"
bsub:
  queue: "gpua100"
  name: "cifar_Rank1"
  gpu_num: 1
  cpu_num: 4
  cpu_mem: 4