hyper:
  lr: 0.01
  epochs: 15
  batch_size: 64
  step_size: 50
  gamma: 0.1
  log_interval: 10
  sigma_prior: 1000
model:
  name: "ConvolutionalBNN"
  #name: "BatchEnsemble_CNN"
  # name: "Simple_rank1_CNN"
  image_size: 32
  #image_size: 28
  num_classes: 10
  # conv_layers: [(3, 64, 3, 1, 1, 0.2, True), (64, 128, 3, 1, 1, 0.2, True), (128, 256, 3, 1, 1, 0.2, True), 
  #                                                  (256, 256, 3, 1, 1, 0.2, False), (256, 256, 3, 1, 1, 0.2, False), (256, 256, 3, 1, 1, 0.2, False)]

# For ConvolutionalBNN layer: [in_channels, out_channels, kernel_size, stride, padding, pooling]
  conv_layers: [[3, 64, 3, 1, 1, True], [64, 128, 3, 1, 1, True], [128, 256, 3, 1, 1, True]]
  #               [256, 256, 3, 1, 1, False], [256, 256, 3, 1, 1, False], [256, 256, 3, 1, 1, False]]


  # conv_layers: [[3, 64, 3, 10, 1, 1, True], [64, 128, 3, 10, 1, 1, True], [128, 256, 3, 10, 1, 1, True],
  #               [256, 256, 3, 10, 1, 1, False], [256, 256, 3, 10, 1, 1, False], [256, 256, 3, 10, 1, 1, False]]
  #conv_layers: [[1, 64, 3, 9, 1, 1], [64, 128, 3, 9, 1, 1], [128, 256, 3, 9, 1, 1]]
  # conv_layers: [[3, 64, 3, 1, 1], [64, 128, 3, 1, 1], [128, 256, 3, 1, 1]]
data:
  dataset_name: "cifar10"
  # dataset_name: "mnist"
constants:
  seed: 42
  patience: 5
  input_dim: 784
  output_dim: 10
  data_path: "data/"
wandb:
  project: "uncertainty_quantification"
  entity: "andr917d"
bsub:
  queue: "gpua100"
  name: "cifar_BNN"
  gpu_num: 1
  cpu_num: 4
  cpu_mem: 4